# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addShell.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from testConnShell import TestConn
from PyQt5 import QtCore, QtGui, QtWidgets
from testConnShell import dns_resolver

class Ui_dialog(QtWidgets.QDialog):
    signal_url_password = QtCore.pyqtSignal(list)
    def __init__(self):
        super().__init__()

        self.initUI()
    def initUI(self):
        self.setObjectName("dialog")
        self.resize(500, 200)
        self.setMinimumSize(QtCore.QSize(500, 200))
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 3, 2, 1)
        self.label_3 = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 3, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 3, 1, 1)


        # 测试连接稳定性
        self.pushButton_2.clicked.connect(self.testConn)
        # 添加数据
        self.pushButton.clicked.connect(self.close)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.setTabOrder(self.lineEdit, self.lineEdit_2)
        self.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        self.setTabOrder(self.lineEdit_3, self.pushButton)
        self.setTabOrder(self.pushButton, self.pushButton_2)
        self.setTabOrder(self.pushButton_2, self.textBrowser)

    def closeEvent(self, event):
        if not hasattr(self.sender(), 'text'):
            event.accept()
        else:
            try:
                ip = dns_resolver(self.lineEdit.text())
                self.signal_url_password.emit([self.lineEdit.text(), self.lineEdit_2.text(), self.lineEdit_3.text()])
                event.accept()
            except Exception as e:
                self.textBrowser.setText('添加失败！\n' + str(Exception(e)))
                event.ignore()

    def testConn(self):
        url = self.lineEdit.text()
        passWord = self.lineEdit_2.text()
        try:
            r = TestConn(url, passWord)
            self.textBrowser.setText('连接成功！\n' + r)
        except Exception as e:
            self.textBrowser.setText('连接失败！\n' + str(Exception(e)))

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "添加shell"))
        self.label.setText(_translate("dialog", "URL链接"))
        self.label_2.setText(_translate("dialog", "密码"))
        self.pushButton_2.setText(_translate("dialog", "测试连接"))
        self.pushButton.setText(_translate("dialog", "添加"))
        self.label_3.setText(_translate("dialog", "备注"))
